version: "3.7"

networks:
  iu_ml_models:
    name: iu_ml_models

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        GUNICORN_TIMEOUT: $GUNICORN_TIMEOUT
    runtime: nvidia
    restart: always
    container_name: desc_en_lstm
    hostname: desc_en_lstm
    volumes:
      - ./logs:/iu_desc_en_lstm/logs
      - $HOST_IMAGE_DIR:$CONTAINER_IMAGE_DIR
    networks:
      - iu_ml_models
    ports:
      - $APP_PORT:8000