version: "3.7"

networks:
  iu_ml_models:
    name: iu_ml_models

services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desc_en_lstm_dev
    hostname: desc_en_lstm
    volumes:
      - .:/iu_desc_en_lstm
      - $HOST_IMAGE_DIR:$CONTAINER_IMAGE_DIR
    networks:
      - iu_ml_models
    ports:
      - $APP_PORT:8000